version: '3.7'

services:
  remote_console:
    image: node:lts-alpine
    container_name: remote_console
    restart: unless-stopped
    volumes:
      - './:/app'
    working_dir: '/app'
    environment:
      NODE_ENV: 'development'
      PORT: 80
    ports:
      - '8080:80/tcp'
      - '8081:8081'
    command: sh -c 'npm install && npm run run'
